In [ ]:
import pandas as pd
df=pd.read_csv("dems.csv")
df.head()

   Group  MR Delay  SES  MMSE  CDR  eTIV   nWBV    ASF
0      0         0    2    27  0.0  1987  0.696  0.883
1      0       457    2    30  0.0  2004  0.681  0.876
2      0         0    3    28  0.0  1215  0.710  1.444
3      0       538    3    27  0.0  1200  0.718  1.462
4      0         0    4    28  0.0  1689  0.712  1.039

In [ ]:

!pip install qiskit scikit-learn

import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from qiskit.circuit import QuantumCircuit, Parameter
from qiskit.circuit.library import ZZFeatureMap, TwoLocal
from qiskit_aer.primitives import Sampler
#from qiskit.utils import algorithm_globals
from qiskit.circuit.random import random_circuit
from qiskit_machine_learning.kernels import FidelityQuantumKernel
from qiskit_machine_learning.algorithms import QSVC

# Set seed for reproducibility
seed = 45

import pandas as pd

df = pd.read_csv('dems.csv')
df.head()
X=df.drop('Group',axis=1)
y=df['Group']
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

"""
# Scale the data (important for feature maps)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
"""
# --- 2. Quantum Kernel Definition ---
# Define a quantum feature map
# ZZFeatureMap is a common choice for QSVC
adhoc_dimension=2
feature_map = ZZFeatureMap(feature_dimension=adhoc_dimension, insert_barriers=True, reps=3,entanglement='full')

# Define the quantum kernel
sampler = Sampler()
adhoc_kernel = FidelityQuantumKernel(feature_map=feature_map)
#quantum_kernel = FidelityQuantumKernel(feature_map=feature_map)

# --- 3. Train and Evaluate the Quantum Support Vector Classifier (QSVC) ---
# Initialize QSVC
qsvc = QSVC(quantum_kernel=adhoc_kernel)

# Train the QSVC model
print("Training QSVC...")
qsvc.fit(X_train, y_train.values.ravel())
print("Training finished.")

# Evaluate the QSVC model
score_qsvc = qsvc.score(X_test, y_test)
print(f"QSVC test accuracy: {score_qsvc}")

# --- (Optional) Compare with a classical SVM ---
print("\nComparing with a classical SVM...")
classical_svm = SVC(kernel='rbf')
classical_svm.fit(X_train, y_train)
score_classical = classical_svm.score(X_test, y_test)
print(f"Classical SVM test accuracy: {score_classical}")
#print(qsvc.predict([5.1,3.5, 1.2, 0.2]))
# --- (Optional) Visualize the Feature Map (requires matplotlib) ---
# !pip install matplotlib
# import matplotlib.pyplot as plt
# from qiskit.visualization import circuit_drawer
# feature_map.draw(output='mpl')
# plt.title("ZZ Feature Map")
# plt.show()

Requirement already satisfied: qiskit in /usr/local/lib/python3.12/dist-packages (1.4.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: rustworkx>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.17.1)
Requirement already satisfied: numpy<3,>=1.17 in /usr/local/lib/python3.12/dist-packages (from qiskit) (2.0.2)
Requirement already satisfied: scipy>=1.5 in /usr/local/lib/python3.12/dist-packages (from qiskit) (1.15.3)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.12/dist-packages (from qiskit) (1.13.3)
Requirement already satisfied: dill>=0.3 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.3.8)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (2.9.0.post0)
Requirement already satisfied: stevedore>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (5.5.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from qiskit) (4.15.0)
Requirement already satisfied: symengine<0.14,>=0.11 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.13.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->qiskit) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.3->qiskit) (1.3.0)
Training QSVC...
Training finished.
QSVC test accuracy: 0.578125

Comparing with a classical SVM...
Classical SVM test accuracy: 0.578125

In [ ]:

!pip install qiskit scikit-learn

import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from qiskit.circuit import QuantumCircuit, Parameter
from qiskit.circuit.library import ZZFeatureMap, TwoLocal
from qiskit_aer.primitives import Sampler
#from qiskit.utils import algorithm_globals
from qiskit.circuit.random import random_circuit
from qiskit_machine_learning.kernels import FidelityQuantumKernel
from qiskit_machine_learning.algorithms import QSVC

# Set seed for reproducibility
seed = 45

import pandas as pd

df = pd.read_csv('dems.csv')
df.head()
X=df.drop('Group',axis=1)
y=df['Group']
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

"""
# Scale the data (important for feature maps)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
"""
# --- 2. Quantum Kernel Definition ---
# Define a quantum feature map
# ZZFeatureMap is a common choice for QSVC
adhoc_dimension=2
feature_map = ZZFeatureMap(feature_dimension=adhoc_dimension, insert_barriers=True, reps=3,entanglement='linear')

# Define the quantum kernel
sampler = Sampler()
adhoc_kernel = FidelityQuantumKernel(feature_map=feature_map)
#quantum_kernel = FidelityQuantumKernel(feature_map=feature_map)

# --- 3. Train and Evaluate the Quantum Support Vector Classifier (QSVC) ---
# Initialize QSVC
qsvc = QSVC(quantum_kernel=adhoc_kernel)

# Train the QSVC model
print("Training QSVC...")
qsvc.fit(X_train, y_train.values.ravel())
print("Training finished.")

# Evaluate the QSVC model
score_qsvc = qsvc.score(X_test, y_test)
print(f"QSVC test accuracy: {score_qsvc}")

# --- (Optional) Compare with a classical SVM ---
print("\nComparing with a classical SVM...")
classical_svm = SVC(kernel='rbf')
classical_svm.fit(X_train, y_train)
score_classical = classical_svm.score(X_test, y_test)
print(f"Classical SVM test accuracy: {score_classical}")
#print(qsvc.predict([5.1,3.5, 1.2, 0.2]))
# --- (Optional) Visualize the Feature Map (requires matplotlib) ---
# !pip install matplotlib
# import matplotlib.pyplot as plt
# from qiskit.visualization import circuit_drawer
# feature_map.draw(output='mpl')
# plt.title("ZZ Feature Map")
# plt.show()

Requirement already satisfied: qiskit in /usr/local/lib/python3.12/dist-packages (1.4.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: rustworkx>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.17.1)
Requirement already satisfied: numpy<3,>=1.17 in /usr/local/lib/python3.12/dist-packages (from qiskit) (2.0.2)
Requirement already satisfied: scipy>=1.5 in /usr/local/lib/python3.12/dist-packages (from qiskit) (1.15.3)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.12/dist-packages (from qiskit) (1.13.3)
Requirement already satisfied: dill>=0.3 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.3.8)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (2.9.0.post0)
Requirement already satisfied: stevedore>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (5.5.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from qiskit) (4.15.0)
Requirement already satisfied: symengine<0.14,>=0.11 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.13.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->qiskit) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.3->qiskit) (1.3.0)
Training QSVC...
Training finished.
QSVC test accuracy: 0.8125

Comparing with a classical SVM...
Classical SVM test accuracy: 0.578125

In [ ]:

!pip install qiskit scikit-learn

import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from qiskit.circuit import QuantumCircuit, Parameter
from qiskit.circuit.library import ZZFeatureMap, TwoLocal
from qiskit_aer.primitives import Sampler
#from qiskit.utils import algorithm_globals
from qiskit.circuit.random import random_circuit
from qiskit_machine_learning.kernels import FidelityQuantumKernel
from qiskit_machine_learning.algorithms import QSVC

# Set seed for reproducibility
seed = 45

import pandas as pd

df = pd.read_csv('dems.csv')
df.head()
X=df.drop('Group',axis=1)
y=df['Group']
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

"""
# Scale the data (important for feature maps)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
"""
# --- 2. Quantum Kernel Definition ---
# Define a quantum feature map
# ZZFeatureMap is a common choice for QSVC
adhoc_dimension=2
feature_map = ZZFeatureMap(feature_dimension=adhoc_dimension, insert_barriers=True, reps=3,entanglement='circular')

# Define the quantum kernel
sampler = Sampler()
adhoc_kernel = FidelityQuantumKernel(feature_map=feature_map)
#quantum_kernel = FidelityQuantumKernel(feature_map=feature_map)

# --- 3. Train and Evaluate the Quantum Support Vector Classifier (QSVC) ---
# Initialize QSVC
qsvc = QSVC(quantum_kernel=adhoc_kernel)

# Train the QSVC model
print("Training QSVC...")
qsvc.fit(X_train, y_train.values.ravel())
print("Training finished.")

# Evaluate the QSVC model
score_qsvc = qsvc.score(X_test, y_test)
print(f"QSVC test accuracy: {score_qsvc}")

# --- (Optional) Compare with a classical SVM ---
print("\nComparing with a classical SVM...")
classical_svm = SVC(kernel='rbf')
classical_svm.fit(X_train, y_train)
score_classical = classical_svm.score(X_test, y_test)
print(f"Classical SVM test accuracy: {score_classical}")
#print(qsvc.predict([5.1,3.5, 1.2, 0.2]))
# --- (Optional) Visualize the Feature Map (requires matplotlib) ---
# !pip install matplotlib
# import matplotlib.pyplot as plt
# from qiskit.visualization import circuit_drawer
# feature_map.draw(output='mpl')
# plt.title("ZZ Feature Map")
# plt.show()

Requirement already satisfied: qiskit in /usr/local/lib/python3.12/dist-packages (1.4.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: rustworkx>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.17.1)
Requirement already satisfied: numpy<3,>=1.17 in /usr/local/lib/python3.12/dist-packages (from qiskit) (2.0.2)
Requirement already satisfied: scipy>=1.5 in /usr/local/lib/python3.12/dist-packages (from qiskit) (1.15.3)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.12/dist-packages (from qiskit) (1.13.3)
Requirement already satisfied: dill>=0.3 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.3.8)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (2.9.0.post0)
Requirement already satisfied: stevedore>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (5.5.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from qiskit) (4.15.0)
Requirement already satisfied: symengine<0.14,>=0.11 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.13.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->qiskit) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.3->qiskit) (1.3.0)
Training QSVC...
Training finished.
QSVC test accuracy: 0.78125

Comparing with a classical SVM...
Classical SVM test accuracy: 0.578125

In [4]:
!pip install qiskit_aer
!pip install qiskit_machine_learning

Collecting qiskit_aer
  Downloading qiskit_aer-0.17.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.3 kB)
Requirement already satisfied: qiskit>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from qiskit_aer) (2.2.3)
Requirement already satisfied: numpy>=1.16.3 in /usr/local/lib/python3.12/dist-packages (from qiskit_aer) (2.0.2)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from qiskit_aer) (1.16.3)
Requirement already satisfied: psutil>=5 in /usr/local/lib/python3.12/dist-packages (from qiskit_aer) (5.9.5)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from qiskit_aer) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->qiskit_aer) (1.17.0)
Requirement already satisfied: rustworkx>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from qiskit>=1.1.0->qiskit_aer) (0.17.1)
Requirement already satisfied: dill>=0.3 in /usr/local/lib/python3.12/dist-packages (from qiskit>=1.1.0->qiskit_aer) (0.3.8)
Requirement already satisfied: stevedore>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from qiskit>=1.1.0->qiskit_aer) (5.5.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from qiskit>=1.1.0->qiskit_aer) (4.15.0)
Downloading qiskit_aer-0.17.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 107.1 MB/s eta 0:00:00
Installing collected packages: qiskit_aer
Successfully installed qiskit_aer-0.17.2
Collecting qiskit_machine_learning
  Downloading qiskit_machine_learning-0.8.4-py3-none-any.whl.metadata (13 kB)
Collecting qiskit<2.0,>=1.0 (from qiskit_machine_learning)
  Downloading qiskit-1.4.5-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Requirement already satisfied: numpy>=2.0 in /usr/local/lib/python3.12/dist-packages (from qiskit_machine_learning) (2.0.2)
Collecting scipy<1.16,>=1.4 (from qiskit_machine_learning)
  Downloading scipy-1.15.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn>=1.2 in /usr/local/lib/python3.12/dist-packages (from qiskit_machine_learning) (1.6.1)
Requirement already satisfied: setuptools>=40.1 in /usr/local/lib/python3.12/dist-packages (from qiskit_machine_learning) (75.2.0)
Requirement already satisfied: dill>=0.3.4 in /usr/local/lib/python3.12/dist-packages (from qiskit_machine_learning) (0.3.8)
Requirement already satisfied: rustworkx>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from qiskit<2.0,>=1.0->qiskit_machine_learning) (0.17.1)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.12/dist-packages (from qiskit<2.0,>=1.0->qiskit_machine_learning) (1.13.3)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from qiskit<2.0,>=1.0->qiskit_machine_learning) (2.9.0.post0)
Requirement already satisfied: stevedore>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from qiskit<2.0,>=1.0->qiskit_machine_learning) (5.5.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from qiskit<2.0,>=1.0->qiskit_machine_learning) (4.15.0)
Collecting symengine<0.14,>=0.11 (from qiskit<2.0,>=1.0->qiskit_machine_learning)
  Downloading symengine-0.13.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2->qiskit_machine_learning) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2->qiskit_machine_learning) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->qiskit<2.0,>=1.0->qiskit_machine_learning) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.3->qiskit<2.0,>=1.0->qiskit_machine_learning) (1.3.0)
Downloading qiskit_machine_learning-0.8.4-py3-none-any.whl (231 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.9/231.9 kB 10.4 MB/s eta 0:00:00
Downloading qiskit-1.4.5-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 67.2 MB/s eta 0:00:00
Downloading scipy-1.15.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 19.6 MB/s eta 0:00:00
Downloading symengine-0.13.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (49.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 MB 15.4 MB/s eta 0:00:00
Installing collected packages: symengine, scipy, qiskit, qiskit_machine_learning
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.3
    Uninstalling scipy-1.16.3:
      Successfully uninstalled scipy-1.16.3
  Attempting uninstall: qiskit
    Found existing installation: qiskit 2.2.3
    Uninstalling qiskit-2.2.3:
      Successfully uninstalled qiskit-2.2.3
Successfully installed qiskit-1.4.5 qiskit_machine_learning-0.8.4 scipy-1.15.3 symengine-0.13.0

In [1]:

!pip install qiskit scikit-learn

import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from qiskit.circuit import QuantumCircuit, Parameter
from qiskit.circuit.library import ZZFeatureMap, TwoLocal
from qiskit_aer.primitives import Sampler
#from qiskit.utils import algorithm_globals
from qiskit.circuit.random import random_circuit
from qiskit_machine_learning.kernels import FidelityQuantumKernel
from qiskit_machine_learning.algorithms import QSVC

# Set seed for reproducibility
seed = 45

import pandas as pd

df = pd.read_csv('dems.csv')
df.head()
X=df.drop('Group',axis=1)
y=df['Group']
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

"""
# Scale the data (important for feature maps)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
"""
# --- 2. Quantum Kernel Definition ---
# Define a quantum feature map
# ZZFeatureMap is a common choice for QSVC
adhoc_dimension=2
feature_map = ZZFeatureMap(feature_dimension=adhoc_dimension, insert_barriers=True, reps=3,entanglement='circular')

# Define the quantum kernel
sampler = Sampler()
adhoc_kernel = FidelityQuantumKernel(feature_map=feature_map)
#quantum_kernel = FidelityQuantumKernel(feature_map=feature_map)

# --- 3. Train and Evaluate the Quantum Support Vector Classifier (QSVC) ---
# Initialize QSVC
qsvc = QSVC(quantum_kernel=adhoc_kernel)

# Train the QSVC model
print("Training QSVC...")
qsvc.fit(X_train, y_train.values.ravel())
print("Training finished.")

# Evaluate the QSVC model
score_qsvc = qsvc.score(X_test, y_test)
print(f"QSVC test accuracy: {score_qsvc}")

# --- (Optional) Compare with a classical SVM ---
print("\nComparing with a classical SVM...")
classical_svm = SVC(kernel='rbf')
classical_svm.fit(X_train, y_train)
score_classical = classical_svm.score(X_test, y_test)
print(f"Classical SVM test accuracy: {score_classical}")
#print(qsvc.predict([5.1,3.5, 1.2, 0.2]))
# --- (Optional) Visualize the Feature Map (requires matplotlib) ---
# !pip install matplotlib
# import matplotlib.pyplot as plt
# from qiskit.visualization import circuit_drawer
# feature_map.draw(output='mpl')
# plt.title("ZZ Feature Map")
# plt.show()

Requirement already satisfied: qiskit in /usr/local/lib/python3.12/dist-packages (1.4.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: rustworkx>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.17.1)
Requirement already satisfied: numpy<3,>=1.17 in /usr/local/lib/python3.12/dist-packages (from qiskit) (2.0.2)
Requirement already satisfied: scipy>=1.5 in /usr/local/lib/python3.12/dist-packages (from qiskit) (1.15.3)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.12/dist-packages (from qiskit) (1.13.3)
Requirement already satisfied: dill>=0.3 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.3.8)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (2.9.0.post0)
Requirement already satisfied: stevedore>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (5.5.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from qiskit) (4.15.0)
Requirement already satisfied: symengine<0.14,>=0.11 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.13.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->qiskit) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.3->qiskit) (1.3.0)
Training QSVC...
Training finished.
QSVC test accuracy: 0.953125

Comparing with a classical SVM...
Classical SVM test accuracy: 0.578125

In [1]:
import pandas as pd
dfs=pd.read_csv("dems.csv")
dfs.head()

   Group  MR Delay  SES  MMSE  CDR
0      0         0    2    27  0.0
1      0       457    2    30  0.0
2      0         0    3    28  0.0
3      0       538    3    27  0.0
4      0         0    4    28  0.0

In [2]:

!pip install qiskit scikit-learn

import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from qiskit.circuit import QuantumCircuit, Parameter
from qiskit.circuit.library import ZZFeatureMap, TwoLocal
from qiskit_aer.primitives import Sampler
#from qiskit.utils import algorithm_globals
from qiskit.circuit.random import random_circuit
from qiskit_machine_learning.kernels import FidelityQuantumKernel
from qiskit_machine_learning.algorithms import QSVC

# Set seed for reproducibility
seed = 45

import pandas as pd

df = pd.read_csv('dems.csv')
df.head()
X=df.drop('Group',axis=1)
y=df['Group']
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

"""
# Scale the data (important for feature maps)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
"""
# --- 2. Quantum Kernel Definition ---
# Define a quantum feature map
# ZZFeatureMap is a common choice for QSVC
adhoc_dimension=2
feature_map = ZZFeatureMap(feature_dimension=adhoc_dimension, insert_barriers=True, reps=3,entanglement='circular')

# Define the quantum kernel
sampler = Sampler()
adhoc_kernel = FidelityQuantumKernel(feature_map=feature_map)
#quantum_kernel = FidelityQuantumKernel(feature_map=feature_map)

# --- 3. Train and Evaluate the Quantum Support Vector Classifier (QSVC) ---
# Initialize QSVC
qsvc = QSVC(quantum_kernel=adhoc_kernel)

# Train the QSVC model
print("Training QSVC...")
qsvc.fit(X_train, y_train.values.ravel())
print("Training finished.")

# Evaluate the QSVC model
score_qsvc = qsvc.score(X_test, y_test)
print(f"QSVC test accuracy: {score_qsvc}")

# --- (Optional) Compare with a classical SVM ---
print("\nComparing with a classical SVM...")
classical_svm = SVC(kernel='rbf')
classical_svm.fit(X_train, y_train)
score_classical = classical_svm.score(X_test, y_test)
print(f"Classical SVM test accuracy: {score_classical}")
#print(qsvc.predict([5.1,3.5, 1.2, 0.2]))
# --- (Optional) Visualize the Feature Map (requires matplotlib) ---
# !pip install matplotlib
# import matplotlib.pyplot as plt
# from qiskit.visualization import circuit_drawer
# feature_map.draw(output='mpl')
# plt.title("ZZ Feature Map")
# plt.show()

Requirement already satisfied: qiskit in /usr/local/lib/python3.12/dist-packages (1.4.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: rustworkx>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.17.1)
Requirement already satisfied: numpy<3,>=1.17 in /usr/local/lib/python3.12/dist-packages (from qiskit) (2.0.2)
Requirement already satisfied: scipy>=1.5 in /usr/local/lib/python3.12/dist-packages (from qiskit) (1.15.3)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.12/dist-packages (from qiskit) (1.13.3)
Requirement already satisfied: dill>=0.3 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.3.8)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (2.9.0.post0)
Requirement already satisfied: stevedore>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from qiskit) (5.5.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from qiskit) (4.15.0)
Requirement already satisfied: symengine<0.14,>=0.11 in /usr/local/lib/python3.12/dist-packages (from qiskit) (0.13.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->qiskit) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.3->qiskit) (1.3.0)
Training QSVC...
Training finished.
QSVC test accuracy: 0.953125

Comparing with a classical SVM...
Classical SVM test accuracy: 0.578125